export enum Colors {
  PRIMARY_DARK_BLUE = '#176B8C',
  SECONDARY_LIGHT_BLUE = '#7CA1BD',
  TERTIARY_GRAY = '#F0F0F0',
  QUARTERNARY_DARK_GRAY = '#5A5D5D',
  QUINARY_LIGHT_GRAY = '#CFCFCF',
  SENARY_RED = '#FF0004',
  SEPTENARY_WHITE = '#FFF',
  HOVER_BLUE = '#125871',
  HOVER_WHITE = '#f4f8fb',
  HOVER_WHITE_TWO = '#fafafa',

}